### ISSUE TITLE
Are you using LiteLLM?

### ISSUE THREAD

**Issue by ishaan-jaff** [ddelange/ddelange#1]
[ 👋 CTO LiteLLM ] 
Hi @ddelange ,
Thanks for starring LiteLLM. Are you using LiteLLM? https://github.com/BerriAI/litellm

**Comment by ddelange** [comment]
Hi :wave: we're currently researching self hosting LLMs versus managed solutions. Thanks for reaching out! Can you point me to your business model?

**Comment by ishaan-jaff** [comment]
Hi @ddelange LiteLLM is fully open sourced - I'd love to help with your problem over call 

Sharing my calendly for your convenience: https://calendly.com/ishaan-berri/30min?month=2023-09
